# Basic dependabot.yml file with minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/CrowdAggregator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/CrowdManager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/CrowdManager"
    schedule:
      interval: "weekly"
