name: opencv-tracking-v3

channels:
  - conda-forge
dependencies:
  - python==3.9.13
  - pip
  - cudatoolkit=11.6
  - cudnn=8.4.1
  - pip:
    - ipykernel
    - wget
    - numpy
    - GitPython
    - scipy
    - matplotlib
    - requests
