name: opencv-tracking-v4

channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip
  - cudatoolkit=11.6
  - cudnn=8.4.1
  - pip:
    - numpy
    - ipykernel
    - seaborn
    - absl-py
    - scipy
    - tensorflow
    - GitPython
    - matplotlib
